language: java

jdk:
  - openjdk17

branches:
  only:
    - main

#Travis CI 서버의 Home
cache:
  directories:    
    - '$HOME/.gradle'

script: "./mangopot/gradlew clean build"

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - "ygy920@gmail.com"

